kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artcd-workspaces
  labels:
    app: "artcd"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: dynamic-nfs
  volumeMode: Filesystem
