---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-event-listener
  labels:
    app: "artcd"
spec:
  serviceAccountName: tekton-triggers-github-sa
  triggers:
    - name: run-update-pipelines-on-merge
      interceptors:
        # - github:
        #     secretRef:
        #       secretName: github-webhook
        #       secretKey: secretToken
        #     eventTypes:
        #       - pull_request
        - cel:
            filter: "body.action in ['opened', 'edited', 'reopened', 'closed']"
      bindings:
        - ref: run-update-pipelines-on-merge-binding
      template:
        name: run-update-pipelines-on-merge-template
